namespace AmparoIndirectoAPI.Model.ViewModels.Enums
{
    public enum EnumEstadoProcesal
    {
        ACTIVO = 1,
        ACUMULADO = 2,
        DECLINADO = 3,
        REACTIVADO = 4,
        EN_REPARACION = 5,
        PENDIENTE_DE_RENDIR_INFORME_PREVIO = 6,
        PENDIENTE_DE_SENTENCIA_INCIDENTAL = 7,
        SENTENCIA_INCIDENTAL = 8,
        PENDIENTE_DE_RESOLUCION_DE_RECURSO_DE_QUEJA_INCIDENTAL = 9,
        PENDIENTE_DE_RESOLUCIÓN_DE_REVISIÓN_INCIDENTAL = 10,
        PENDIENTE_DE_RESOLUCION_DE_INCIDENTE = 11,
        PENDIENTE_DE_SENTENCIA_CONSTITUCIONAL = 12,
        PENDIENTE_DE_FIRMEZA = 13,
        PENDIENTE_DE_CUMPLIMIENTO_DE_FALLO = 14,
        PENDIENTE_DE_RESOLUCIÓN_DE_RECURSO_DE_QUEJA_PRINCIPAL = 15,
        PENDIENTE_DE_RESOLUCIÓN_DE_REVISIÓN_PRINCIPAL = 16,
        PENDIENTE_DE_RESOLUCIÓN_DE_RECURSO_DE_INCONFORMIDAD = 17,
        PENDIENTE_DE_RESOLUCION_DE_RECURSO_DE_RECLAMACION = 18,
        CONCLUIDO = 19,
    }
}
